#!/bin/bash

# chkconfig: 35 10 10
# description: Remove AWS Instance from IPA server on shutdown
# place this in /etc/init.d and then run chkconfig --add removefromipa
#

. /etc/init.d/functions
lockfile=/var/lock/subsys/removefromipa

case "$1" in
    start)
        touch $lockfile
        ;;
    stop)
        /usr/sbin/ipa-join -u 1> /tmp/removeipa 2>&1
        rm -f $lockfile
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0 
